[workspace]
members = ["build", "errors", "sys"]
resolver = "2"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
debug = false
panic = "abort"

[profile.release.package."*"]
opt-level = 3
codegen-units = 1
debug = false
